apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis # Must match Service selector
spec:
  containers:
    - name: redis-container
      image: redis:latest
      ports:
        - containerPort: 6379
